### ISSUE TITLE
Does blob works with download

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-shell#1]
Does blob works with download: url/*
It would be very nice.

But may be I don't understand blob and returns only triple and has to be used with fetch

**Comment by jeff-zucker** [comment]
Yes, blobs work with downloads.  However there are some other problems with download. I'm working on it.

**Comment by jeff-zucker** [comment]
OK,  here's the current situation: latest solid-shell can download blobs (binary data e.g. a zip or png file) and other single files but it can not yet download a glob of files ( url/*) of any kind.  I will implement that as part of including rdflib into solid-shell which can't really happen until solid-auth-cli is included in rdflib.  So it may be a while.

**Comment by jeff-zucker** [comment]
As of version 1.x, blobs are fully supported.  Globs are not but commands on folders apply recursively which provides similar results.
