### ISSUE TITLE
How can I empty a folder with sol?

### ISSUE THREAD

**Issue by phochste** [jeff-zucker/solid-shell#13]
For my experiments I want to clean my LDN inbox at regular intervals. When I do:

```
npx sol -l recursiveDelete /inbox
```

then, not only the contents of the inbox is deleted but also the inbox itself. Is there a way to clean the folder but not throw the folder itself away?

**Comment by jeff-zucker** [comment]
Interesting point.  Currently, you have to delete the folder and its contents.  The underlying library (solid-file-client) does have a method to recursively delete contents but not the folder so it shouldn't be too hard to add to solid-shell.
