### ISSUE TITLE
solid-shell keeps asking for base folder, even if SOLID_BASE is given

### ISSUE THREAD

**Issue by angelo-v** [jeff-zucker/solid-shell#5]
I set all the env variables stated in the readme including SOLID_BASE. All questions are skipped as expected, except for `base folder?`, which is showing up still.

In [this line](https://github.com/jeff-zucker/solid-shell/blob/master/src/sol.run.js#L245) it trys to get the base from solid-auth-cli, but if I see this correctly solid-auth-cli does not provide it

**Comment by jeff-zucker** [comment]
Ooops, thanks.  I'll patch that in solid-shell and solid-auth-cli too.

**Comment by jeff-zucker** [comment]
Fixed when using solid-auth-cli 0.1.11, just npm'd.
