### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/solid-shell#6]
Windows 10 
node v12.16.0

C:\Users\Smag\Documents\dev\solid-shell>sol shell
'sol' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Smag\Documents\dev\solid-shell>./sol shell
'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Smag\Documents\dev\solid-shell>dir
 Le volume dans le lecteur C s’appelle Local Disk
 Le numéro de série du volume est B2B5-8101

 Répertoire de C:\Users\Smag\Documents\dev\solid-shell

16/02/2020  21:10    <DIR>          .
16/02/2020  21:10    <DIR>          ..
16/02/2020  21:10                53 .gitignore
16/02/2020  21:10             1 089 LICENSE
16/02/2020  21:10    <DIR>          node_modules
16/02/2020  21:10            29 696 package-lock.json
16/02/2020  21:10               481 package.json
16/02/2020  21:10             5 764 README.md
16/02/2020  21:10             2 170 sol
16/02/2020  21:10    <DIR>          src
               6 fichier(s)           39 253 octets
               4 Rép(s)  10 386 415 616 octets libres

C:\Users\Smag\Documents\dev\solid-shell>sol
'sol' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

C:\Users\Smag\Documents\dev\solid-shell>sol shell
'sol' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Smag\Documents\dev\solid-shell>node sol
logging in ...
error logging in : TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

C:\Users\Smag\Documents\dev\solid-shell>node sol shell
logging in ...
error logging in : TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

C:\Users\Smag\Documents\dev\solid-shell>

**Comment by jeff-zucker** [comment]
Hmm, I've had no reports of anything like this.  Can putting your info in this script and then run it: 
```javascript
let auth = require('solid-auth-cli')
let me = {
  username : "jeffz",
  idp      : "https://solid.community",
  password : "",
}
async function run(){
  console.log("logging in ...")
  await auth.login(me)
  let session = await auth.currentSession()
  console.log(
    session ? `logged  in as <${session.webId}>` : "not logged in"
  )
}
run()
```

**Comment by scenaristeur** [comment]
got the same error with RSASSA-PKCS1-v1_5.js: but it seems that i got an issue with node-gyp, perharps since i've migrated from nodev10 to 12. must investigate on my side first ;-)

**Comment by jeff-zucker** [comment]
There is now a new version of solid-auth-cli v0.1.11 which fixes several issues, please let me know if this is still happening for you.

**Comment by scenaristeur** [comment]
C:\Users\Smag\Documents\dev\solid-shell>npx sol
npx: installed 1 in 5.328s
command not found: sol

C:\Users\Smag\Documents\dev\solid-shell>node sol
logging in ...
base folder? https://spoggy.solid.community/public
error logging in : AssertionError [ERR_ASSERTION]: Missing scope parameter in authentication request

C:\Users\Smag\Documents\dev\solid-shell>

But don't worry for me, it's not my priority ;-)

**Comment by jeff-zucker** [comment]
There are ongoing difficulties in the chain of modules beneath solid-auth-cli ... I think the very latest solid-auth-cli should work, but I recommend you erase your node_modules in the solid-shell folder, then npm install to get the latest everything.

**Comment by jeff-zucker** [comment]
Have not heard reports of this on recent versions, closing for now
